### ISSUE TITLE
compile error - simple.ino

### ISSUE THREAD

**Issue by pvdw0310** [nrwiersma/ConfigManager#45]
When I compile the sample - simple.ino I get a compile error !

C:\Users\peter\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\DNSServer\src/DNSServer.h:67:13: error: cannot declare field 'DNSServer::_udp' to be of abstract type 'WiFiUDP'

     WiFiUDP _udp;

             ^
Any idea what I did wrong?
Many thanks,

**Comment by nrwiersma** [comment]
Hi,

Your problem is not with ConfigManager but with compiling the esp8266 libs in general.

It is more than likely something wrong with your setup, like you are compiling against the wrong target or something like that, so it cannot figure out the correct UDP code to use, that would be my guess anyway. I would suggest you look to the esp8266 Arduino forums for help here.

Sorry i cannot be of more help.
